### ISSUE TITLE
Error running: "Node.js 16 actions are deprecated."

### ISSUE THREAD

**Issue by rcoenen** [adriantombu/twitter-cleaning#10]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by adriantombu** [comment]
Hey there, thanks for letting me know! I haven't used Twitter for quite a while but this was an easy fix https://github.com/adriantombu/twitter-cleaning/commit/3cec41153a191f44fa99c0fb1d45463d09bc56fe ☺️
