### ISSUE TITLE
Retweets support?

### ISSUE THREAD

**Issue by le-jun** [adriantombu/twitter-cleaning#5]
Just to be sure, retweets aren’t supported?

At this point my account is pretty much cleared but I’ve still got many retweets appearing on my profile. That good enough for my case but I was curious to know what could be the reason behind not supporting deleting RTs.

**Comment by adriantombu** [comment]
Hey @le-jun!

Retweets and quote retweets are part of the user timeline and should be deleted without any problem. I just made a test with my account, and they were removed successfully. I also deleted an account with 5k tweets/retweets a few weeks ago, with a timeline going back to 2016.

On top of my head, I only see one potential reason for your problem: the retweets that are still showing on your profile are the most recent ones, and they don't meet the threshold of 14 days to be deleted (you can set `DELETE_AFTER_DAYS` to `0` to avoid that).

If it's not that, maybe it's an API limitation I'm not aware of 🙈

**Comment by le-jun** [comment]
Well, everything has been cleaned except retweets older than 2021, so I guess that yet another thing coming from the API. Thanks anyway!
