### ISSUE TITLE
Can't configure repository correctly

### ISSUE THREAD

**Issue by galaxy-nomad** [adriantombu/twitter-cleaning#6]
Hello,
Is it possible to do a video going through the steps to setup this repository? I tried to follow through but had several issues and running the workflow ultimately failed. When I try to save your env.example values as a new secret all of my changes are erased and the secret is empty after saving. If I save your env.example values as an environment variable the values are there after saving but the workflow fails when I run it.

**Comment by adriantombu** [comment]
Hey @cyberfunk, I'm sorry to see you struggle! Someone else had a similar problem a few months ago, I hope the answers I provided then will be helpful 😊

https://github.com/adriantombu/twitter-cleaning/issues/4

**Comment by galaxy-nomad** [comment]
> Hey @cyberfunk, I'm sorry to see you struggle! Someone else had a similar problem a few months ago, I hope the answers I provided then will be helpful 😊
> 
> 
> 
> https://github.com/adriantombu/twitter-cleaning/issues/4

All good man. I used another GitHub project and it worked so well I was a little bit shocked. I thought accessing the API was a paid affair but I was able to completely wipe out my 5000+ timeline in one go free of charge.

**Comment by galaxy-nomad** [comment]
This is the one I used. https://github.com/koenrh/delete-tweets

**Comment by adriantombu** [comment]
Good to hear! And yeah, I think they haven't pushed their crazy pricing yet for the API, you got lucky 😎
